spring:
  application:
    name: server
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: false
    properties:
      hibernate:
        format_sql: true
